In [1]:
import numpy as np
import pandas as pd

In [2]:
a=np.array([1,2,3,4,5,6])

In [3]:
a

array([1, 2, 3, 4, 5, 6])

In [4]:
a.ndim

1

In [5]:
a.size

6

In [6]:
a.dtype

dtype('int32')

In [7]:
a.itemsize

4

In [8]:
a.min

<function ndarray.min>

In [9]:
a.max

<function ndarray.max>

In [10]:
a.shape

(6,)

In [11]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.arange

<function numpy.arange>

In [13]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [14]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [15]:
a

array([1, 2, 3, 4, 5, 6])

In [19]:
a.reshape(3,2
        )

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
a.ravel

<function ndarray.ravel>

In [21]:
a

array([1, 2, 3, 4, 5, 6])

In [22]:
a.sum


<function ndarray.sum>

In [23]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [24]:
b=np.array([2,4,6,8])

In [25]:
a

array([1, 2, 3, 4, 5, 6])

In [26]:
b

array([2, 4, 6, 8])

In [29]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
a=np.array([[1,2],[3,4],[5,6]])

In [33]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
a.ravel

<function ndarray.ravel>

In [36]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [37]:
a.min()

1

In [38]:
a.max()

6

In [39]:
a


array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
a.sum()

21

In [43]:
a.sum(axis=0)

array([ 9, 12])

In [44]:
a.sum(axis=1)

array([ 3,  7, 11])

In [45]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [46]:
np.std(a)

1.707825127659933

In [47]:
np.mean(a)

3.5

In [48]:
a=np.array([[1,2],[3,4],[5,6]])

In [49]:
b=np.array([[10,20],[30,40],[50,60]])

In [50]:
a+b

array([[11, 22],
       [33, 44],
       [55, 66]])

In [51]:
a-b

array([[ -9, -18],
       [-27, -36],
       [-45, -54]])

In [52]:
a*b

array([[ 10,  40],
       [ 90, 160],
       [250, 360]])

In [53]:
a/b

array([[0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1]])